# Generated by Django 4.1.4 on 2023-01-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="media")),
                ("post", models.CharField(max_length=300)),
                ("comment", models.TextField()),
                ("star", models.IntegerField()),
            ],
        ),
    ]
